testthat::test_that("workflow references are actual exact job declarations", {
  root <- normalizePath(file.path("..", ".."))
  e <- new.env()
  expr <- parse(file.path(root, "tools", "drift.R"))
  for (z in head(expr, -1L)) eval(z, e)
  path <- tempfile()
  dir.create(file.path(path, ".github", "workflows"), recursive = TRUE)
  on.exit(unlink(path, recursive = TRUE))
  file <- file.path(path, ".github", "workflows", "R-CMD-check.yml")
  ref <- "gojiplus/r-canon/.github/workflows/reusable-check.yml"
  writeLines(paste0("# uses: ", ref, "@v2"), file)
  testthat::expect_false(identical(e$references(path, "check"), "ok"))
  writeLines(paste0("jobs:\n  check:\n    uses: ", ref, "@v20"), file)
  testthat::expect_false(identical(e$references(path, "check"), "ok"))
  writeLines(paste0("jobs:\n  check:\n    uses: ", ref, "@v2"), file)
  testthat::expect_identical(e$references(path, "check"), "ok")
  writeLines("jobs: [unclosed", file)
  testthat::expect_identical(e$references(path, "check"), "invalid-yaml")
})
